name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu, windows and macos, latest Julia versions (mac on arm, others on x64)
          - os: ubuntu-latest
            arch: x64
            version: "1"
          - os: windows-latest
            arch: x64
            version: "1"
          # macOS - aarch64 (ARM) only, both Julia versions
          - os: macOS-latest
            arch: aarch64
            version: "1"
          # Also test Julia 1.10 on windows for retrocompatibility (most common OS)
          - os: windows-latest
            arch: x64
            version: "1.10"
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      #- uses: julia-actions/julia-buildpkg@latest
      #- uses: julia-actions/julia-runtest@latest

      - uses: julia-actions/julia-buildpkg@v1
      #- uses: julia-actions/julia-runtest@v1


